### ISSUE TITLE
[feature] support wildcard or dynamic prompt to output more different results

### ISSUE THREAD

**Issue by AhBumm** [xlinx/sd-webui-decadetw-auto-prompt-llm#13]
maybe Read the input field of the prompt directly as llm prompt will be a good way

and vision llm seems not working, with error log:
```
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "E:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "E:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\image.py", line 197, in preprocess
    return image_utils.format_image(
  File "E:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
```

thanks for your great work！

**Comment by AhBumm** [comment]
a new problems. when multi batch will use the 1 prompt from the first batch. i can't just roll many image in different scene.

**Comment by AhBumm** [comment]
and import setting seems not work
![image](https://github.com/user-attachments/assets/55df7028-430d-4057-82df-86709d763121)

**Comment by AhBumm** [comment]
> > maybe Read the input field of the prompt directly as llm prompt will be a good way
> 
> do u mean sd-prompt directly for llm-user-prompt?
> 
> I feel sd-prompt leave for pytorch vae lanten space keyword. Ex 1girl. llm-user-prompt leave for human us use. Is it better right?

yes, sd-prompt directly for llm-user-prompt maybe easier to support wildcard. pytorch vae lanten space keyword seems not that important for flux. only use the Natural language could also get a great image

**Comment by xlinx** [comment]
1. okie, after FLUX i seems have the same feeling too, therfor add a checkbox like  [USE SD-PROMPT AS LLM-PROMPT]? 

2. the vision issue, sd-web-ui work well but forge show the error above(TypeError: save_pil_to_file() got an unexpected keyword argument 'name')? let me install forge try it.

**Comment by AhBumm** [comment]
> 1. okie, after FLUX i seems have the same feeling too, therfor add a checkbox like  [USE SD-PROMPT AS LLM-PROMPT]?
> 2. the vision issue, sd-web-ui work well but forge show the error above(TypeError: save_pil_to_file() got an unexpected keyword argument 'name')? let me install forge try it.
> 
> > issue2 should be ok now. [hotfix] change gradio.Image type from path to PIL.Image avoid copy paste img source wo a real file obj.

import setting and vision llm work after update! 🎉🎉

**Comment by AhBumm** [comment]
> 1. okie, after FLUX i seems have the same feeling too, therfor add a checkbox like  [USE SD-PROMPT AS LLM-PROMPT]

oh! we still need a place to input <lora> and lora tag.
add a checkbox like  [USE SD-PROMPT AS LLM-PROMPT] seems not the best way to do. my bad

**Comment by xlinx** [comment]
> > 1. okie, after FLUX i seems have the same feeling too, therfor add a checkbox like  [USE SD-PROMPT AS LLM-PROMPT]
> 
> oh! we still need a place to input lora name and lora tag. add a checkbox like [USE SD-PROMPT AS LLM-PROMPT] seems not the best way to do. my bad

oh~ i forgot it too; 

u can try new feature LLM-Text-Loop
![螢幕擷取畫面 2024-09-04 170623](https://github.com/user-attachments/assets/6a874126-59f1-4bef-9c49-a88d07f89003)
![螢幕擷取畫面 2024-09-04 170929](https://github.com/user-attachments/assets/eaadd1fd-df9d-4881-b68b-85c95b7e6df6)
![螢幕擷取畫面 2024-09-04 171136](https://github.com/user-attachments/assets/fb66a7df-363f-4566-ad2d-7be3a72bea64)
![螢幕擷取畫面 2024-09-04 171311](https://github.com/user-attachments/assets/ffbe72f7-6a73-4503-9ad2-95bd2cf9aea9)

**Comment by AhBumm** [comment]
> > > 1. okie, after FLUX i seems have the same feeling too, therfor add a checkbox like  [USE SD-PROMPT AS LLM-PROMPT]
> > 
> > 
> > oh! we still need a place to input lora name and lora tag. add a checkbox like [USE SD-PROMPT AS LLM-PROMPT] seems not the best way to do. my bad
> 
> oh~Lora... i forgot it too;
> 
> u can try new feature LLM-Text-Loop ![螢幕擷取畫面 2024-09-04 170623](https://private-user-images.githubusercontent.com/1484613/364311417-6a874126-59f1-4bef-9c49-a88d07f89003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDUwMzEsIm5iZiI6MTcyNTUwNDczMSwicGF0aCI6Ii8xNDg0NjEzLzM2NDMxMTQxNy02YTg3NDEyNi01OWYxLTRiZWYtOWM0OS1hODhkMDdmODkwMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDI1MjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODlmOThkOGJmZDVmNmQ0YzRmYWQ5N2IxMTIyYTgxZjk3MzMyODA4OTJhMWVkYjhkMzA2NWUyYTg0YzcwOTkyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-uIiqOaK_WXHeKYfVfisXg624H8DYHa5w4sQY3MvZ5M) ![螢幕擷取畫面 2024-09-04 170929](https://private-user-images.githubusercontent.com/1484613/364311435-eaadd1fd-df9d-4881-b68b-85c95b7e6df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDUwMzEsIm5iZiI6MTcyNTUwNDczMSwicGF0aCI6Ii8xNDg0NjEzLzM2NDMxMTQzNS1lYWFkZDFmZC1kZjlkLTQ4ODEtYjY4Yi04NWM5NWI3ZTZkZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDI1MjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQzOThiY2U1NWQ3ZTlkMjVlYjBiMDIwODY0YjE1YTViOTRjYmZkZWYzYzEyYzNhOThlN2I0NDA5ZjlkZDdhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IkaaB2BHR0zXgUA3WdaVAqLqU2CL7T-vp8jDMuvOfkk) ![螢幕擷取畫面 2024-09-04 171136](https://private-user-images.githubusercontent.com/1484613/364311442-fb66a7df-363f-4566-ad2d-7be3a72bea64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDUwMzEsIm5iZiI6MTcyNTUwNDczMSwicGF0aCI6Ii8xNDg0NjEzLzM2NDMxMTQ0Mi1mYjY2YTdkZi0zNjNmLTQ1NjYtYWQyZC03YmUzYTcyYmVhNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDI1MjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYyNTkxZGU5YzMzZmVlMGZkNmYzMmI0YmNlYWM2ZjBiZTlkYTE0ZTYwYWIyMjU3ZGY3ZWY4YTI1ZTc5OGIwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TUVu3kD-1lmfj5xT2-yg4OQEdtUMbO4I3LAgiK-vsrw) ![螢幕擷取畫面 2024-09-04 171311](https://private-user-images.githubusercontent.com/1484613/364311447-ffbe72f7-6a73-4503-9ad2-95bd2cf9aea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDUwMzEsIm5iZiI6MTcyNTUwNDczMSwicGF0aCI6Ii8xNDg0NjEzLzM2NDMxMTQ0Ny1mZmJlNzJmNy02YTczLTQ1MDMtOWFkMi05NWJkMmNmOWFlYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDI1MjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRkZDUwZGRlMThmNDNiODVhNmIzMWQwNjIxYjAyMTZhOGEyMGJiNTA0YWIwZjRiMzhlZDYwZGM2NzJiNWFjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FyYmG9CrCdQElutlM0FzMQoZkh3GCWRPK1em9d1Vaw4)

i tried that feature, but i don't understand how it work🥲, and it seems to break the system prompt of [LLM-text]

**Comment by AhBumm** [comment]
> a new problems. when multi batch will use the 1 prompt from the first batch. i can't just roll many image in different scene.

I use a js to do this job😂
```
let clickCount = 0;
function clickButton() {
    var generateButton = document.querySelector("#txt2img_generate");

    if (generateButton) {
        generateButton.click();
        console.log('clicked');
        
        clickCount++;
        
        //       click times ↓
        if (clickCount < 10) {
            setTimeout(clickButton, 90000); // wait 90s to next click 
        } else {
            console.log('done!');
        }
    } else {
        console.warn('button not found');
    }
}

clickButton();
```

**Comment by AhBumm** [comment]
> * batch mean same prompt with different random seed.
> * u can try Before after action
> * whats ur purpose ?
> * why not just rightClick on Generate  choice Generate forever

1. every image with Different LLM-Answer prompt was best, or in every batch count have Different prompt from LLM-Answer, not different random seed
2. I tried Before after action. it need user to write a file to replace [LLM-Your-Prompt]
3. I want in the same [LLM-Your-Prompt]，but each batch count or single image could have Different prompt from LLM-Answer
4. I tried rightClick on Generate choice Generate forever, but all the image use the same LLM-Answer prompt. And with js scripts single click will be more LLM-Answer for each batch of t2i gen

**Comment by xlinx** [comment]
- batch=2 -> click gen -> llm-ans1 -> image1(llm-ans-1) , image2(llm-ans-1) | same content but different style.
- next time gen click -> llm-ans2 got 2 image same prompt 2 style
- work like above, that is not u expect？

![螢幕擷取畫面 2024-09-07 132046](https://github.com/user-attachments/assets/bb15b2d7-ec94-4f37-a8c6-ed7ef98655c3)

**Comment by AhBumm** [comment]
> * batch=2 -> click gen -> llm-ans1 -> image1(llm-ans-1) , image2(llm-ans-1) | different content same style.
> * next time gen click -> llm-ans2 got 2 image same prompt same style
> * work like above, that is not u expect？
> 
> ![螢幕擷取畫面 2024-09-07 132046](https://private-user-images.githubusercontent.com/1484613/365344043-bb15b2d7-ec94-4f37-a8c6-ed7ef98655c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDUyMjMsIm5iZiI6MTcyNTcwNDkyMywicGF0aCI6Ii8xNDg0NjEzLzM2NTM0NDA0My1iYjE1YjJkNy1lYzk0LTRmMzctYThjNi1lZDdlZjk4NjU1YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDdUMTAyODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDIwYTYxN2VjYjljNTNkZTY1OTMwN2M3OTcxOThhZmQ2ZTFkM2Y1ZWQ1ZTc4NjlkNDRlOGExNTg1N2IwYzRkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aIscFVMSCK8W3qiIIlJAbJhBwBlRMTNrFEU6ajeAqR0)

* i expect: set batch count=3 -> click gen -> llm-ans1>batch1, llm-ans2>batch2, llm-ans3>batch3

* but now was: batch count=3 -> click gen -> llm-ans1>batch1,2,3 (3image in completely same prompt), //not expect

I think the Advantages of Auto LLM is to generate many prompts. More batches should get more different prompts. Not many pictures in a same prompt. is not much different from using llm externally and copy into the webui.
