### ISSUE TITLE
[BUG] cant run addon

### ISSUE THREAD

**Issue by Rogal80** [xlinx/sd-webui-decadetw-auto-prompt-llm#20]
Hi, 

after instaling all nessesery soft - LM studio and run server 1234 , i get this log in stable diffusion latest version (Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2)

Error loading script: auto_prompt_llm.py
    Traceback (most recent call last):
      File "I:\Github\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "I:\Github\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "I:\Github\stable-diffusion-webui\extensions\sd-webui-decadetw-auto-prompt-llm\scripts\auto_prompt_llm.py", line 11, in <module>
        from openai import OpenAI, OpenAIError
    ImportError: cannot import name 'OpenAI' from 'openai' (I:\Github\stable-diffusion-webui\venv\lib\site-packages\openai\__init__.py)

did i missing something ?

**Comment by xlinx** [comment]
test is base on [Releases](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases) [v1.10.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.10.0)
but its seems like small error on ur version v1.10.1 test is on 1.10.0 , that should be auto install openAI lib.
u can try install by manual.
open cmd ont ur stable python venv and type : pip install OpenAI
i will try install v1.10.1 later or remove lib(OpenAI) dependence later
