### ISSUE TITLE
 [Forge] - Save_pil_to_file() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by CCpt5** [xlinx/sd-webui-decadetw-auto-prompt-llm#7]
Thank you for your efforts on this project! I'm excited to get it running properly.

The LLM text generation seems to work fine, but when I try to use the vision tab I get the below error. Once this occurs the text tab stops working as well and errors with the same error showing up in the console (until resetting Forge)

I know Forge is going through a ton of code reworks right now so if this is due to that, or user error, please forgive me. I wanted to report this error in the event it is a bug that can be tweaked.

One other thing, I **think** there may be a typo on the setup page for this line, "API-ModelName: LMStudio can be empty is fine select in LMStudio App; ollama should set like: ollama3.1 (cmd:ollama list)." The example there says "ollama should set like: ollama3.1" - but I think that should say "llama3.1". I wanted to mention that because if it is a typo, it could lead to confusion regarding what to put in the model field below. I used "llama3.1" as I have that model and that worked fine for the LLM text portion.

Thanks for any insight!!

### Error Log
```plaintext
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\image.py", line 197, in preprocess
    return image_utils.format_image(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
```

<details>
<summary>System Info</summary>
<p>

[sysinfo-2024-08-18-20-05.json](https://github.com/user-attachments/files/16651629/sysinfo-2024-08-18-20-05.json)

</p>
</details>
```

**Comment by xlinx** [comment]
cool, You ask chatgpt this question? haha

**Comment by tazztone** [comment]
the extension used to work a few days ago. but now i have this same error:

```
Traceback (most recent call last):
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\components\image.py", line 197, in preprocess
    return image_utils.format_image(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
```
